[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "clarity"
version = "0.1.0"
description = "tool to give you clarity on your gpay expenses"
authors = ["Jenish Jain"]

[tool.poetry.dependencies]
python = "~3.11 || ^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"